# Generated by Django 4.2.5 on 2023-09-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='rate',
            new_name='date',
        ),
    ]
