# Generated by Django 4.2.5 on 2023-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_carmake_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
